Implement IR feature on HH schema
ONSdigital/eq-questionnaire-schemas pull request #155
Opened 2020-09-08 22:06 UTC by LJBabbage

### What is the context of this PR?

Add IR to all household schemas

### How to review

Check the IR option is available on each schema

### Checklist

- [ ] Jsonnet files conform to the latest [style guide](/ONSdigital/eq-questionnaire-schemas/blob/master/style_guide.md)

### Quick Launch

#### England

- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=H&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-ir-hh/schemas/en/census_household_gb_eng.json)

- [CCS](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-ENG&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-ir-hh/schemas/en/ccs_household_gb_eng.json)

#### Northern Ireland

- [Household](https://test-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&form_type=I&region_code=GB-NIR&url=https://storage.googleapis.com/eq-questionnaire-schemas-artifacts/implement-ir-hh/schemas/en/census_household_gb_nir.json)

2020-09-09 08:04 UTC, berroar approved these changes

2020-09-10 08:38 UTC, MebinAbraham requested changes

2020-09-10 08:38 UTC, MebinAbraham commented on source/jsonnet/england-wales/ccs_household.jsonnet
> +  },
Individual response doensn't apply to CCS?

2020-09-10 09:14 UTC, MebinAbraham approved these changes

2020-09-10 09:39 UTC, merged