Remove census schema files and add business and social files
ONSdigital/eq-questionnaire-schemas pull request #248
Opened 2021-11-08 15:27 UTC by rmccar

### What is the context of this PR?

This PR removes the census schema files and adds business and social files

### How to review

Check changes make sense and reflect what is on the [trello card](https://trello.com/c/tBK7UtE0/4956-eq-questionnaire-schemas-remove-census-schema-files-and-add-business-and-social-files-1-sp)

2021-11-09 15:42 UTC, MebinAbraham reviewed
- The `jsonnet` source files are still there but needs to be removed.
- The README text doesn't quite make sense, as it still refers to building a schema etc. This repo is just a registry now.
- I know the card says `schema` but I think the `schema` dir should be renamed to `schemas` since it will contain multiple schemas. That is also what it used to be.

2021-11-10 13:24 UTC, LJBabbage requested changes
My schemas folder doesn't look how I was expecting, I have this 
![image](https://user-images.githubusercontent.com/14179817/141120899-18e534c2-bc63-43a0-a158-b1e4ff903f7f.png)
I was thinking there was going to a business and social folder with all the census schemas removed

2021-11-10 13:46 UTC, LJBabbage commented
> My schemas folder doesn't look how I was expecting, I have this

Ok, I see why there isn't a schemas folder now, but shouldn't there be?

2021-11-10 13:56 UTC, rmccar commented
> > My schemas folder doesn't look how I was expecting, I have this
> 
> Ok, I see why there isn't a schemas folder now, but shouldn't there be?

Looks like the folder hasn’t been checked in because its being ignored even though it isn't listed in gitignore

2021-11-10 13:58 UTC, rmccar commented
> > > My schemas folder doesn't look how I was expecting, I have this
> > 
> > 
> > Ok, I see why there isn't a schemas folder now, but shouldn't there be?
> 
> Looks like the folder hasn’t been checked in because its being ignored even though it isn't listed in gitignore

Found it. Ill add the folder and gitignore change now

2021-11-11 11:05 UTC, LJBabbage approved these changes

2021-11-11 11:09 UTC, MebinAbraham reviewed
Whoops forgot to post this.

2021-11-12 08:39 UTC, MebinAbraham approved these changes

2021-11-12 08:39 UTC, MebinAbraham commented on README.md
>  You should now be able launch a questionnaire using one of the schemas.
```suggestion
You should now be able to launch a questionnaire using one of the schemas.
```

2021-11-12 13:35 UTC, merged