Publish Bricks
ONSdigital/eq-questionnaire-schemas pull request #462
Opened 2024-01-05 11:23 UTC by kayloshai

### What is the context of this PR?
Describe what you have changed and why, link to other PRs or Issues as appropriate.

### How to review
Describe the steps required to test the changes (include screenshots if appropriate).
[Jira Ticket](https://jira.ons.gov.uk/browse/EAR-2330)

2024-01-05 12:50 UTC, sudeepkunhis submitted a review, later dismissed

2024-01-05 13:07 UTC, martyncolmer requested changes

2024-01-05 13:07 UTC, martyncolmer commented on schemas/business/en/bricks_0003.json
> +    "title": "TEST USE ONLY Monthly Survey of Building Materials - Bricks",
Can you remove for test use only

2024-01-05 14:11 UTC, sudeepkunhis approved these changes

2024-01-08 11:51 UTC, martyncolmer approved these changes

2024-01-08 12:16 UTC, merged